import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import WithHeader from "./components/header";
import Script from "next/script";
import Footer from "./components/footer";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Medicare",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <Script src="/js/font-awesome.js" strategy="lazyOnload" />
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <StoreProvider>
                    <WithHeader>{children}</WithHeader>
                    <Footer />
                </StoreProvider>
            </body>
        </html>
    );
}

// globalThis.info
// window.info

declare global {
    interface globalThis {
        info: () => void | null[] | null;
    }
}

// window.inf
// global.info = () => {}

// https://medsurgeindia.com/
