import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import StoreProvider from './StoreProvider';
import WithHeader from './components/header';
import Script from 'next/script';
import Footer from './components/footer';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Medicare',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning={true}>
            <Script
                // strategy='beforeInteractive'
                // src='https://kit.fontawesome.com/11e3e6af90.js'
                // crossOrigin='anonymous'
                src='/js/font-awesome.js'
            />
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <StoreProvider>
                    <WithHeader>{children}</WithHeader>
                    <Footer />
                </StoreProvider>
            </body>
        </html>
    );
}

// declare global{
//     interface Window{
//         asset:function (endpoint='', slash =true) {
//             return process.env.NEXT_PUBLIC_MAIN_URL + '/'+endpoint;
//         }
//     }
// }
// global.d.ts
